import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "@/theme/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Aqqire | Formerly The Hotel Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} antialiased bg-background`
        )}
      >
        {children}
      </body>
    </html>
  );
}
